### ISSUE TITLE
migrating 1 label Gmail to G Suite

### ISSUE THREAD

**Issue by mixali0s** [imapsync/imapsync#105] opened 2017-09-01 13:00 UTC
Hi,
I managed to sync **only one label** from Gmail to G Suite, wich seems not to work with Google Suite Email Migration tool. Here is how:

1) The 2-step verification is OFF:

https://myaccount.google.com/security?hl=en&pli=1&nlr=1#signin

2) Access for less secure apps is turned ON (both in Gmail and in G Suite. In G Suite you need to enable it from the Admin account, and then turn it ON from the user account):

https://www.google.com/settings/security/lesssecureapps
https://support.google.com/accounts/answer/6010255?hl=en

2) execute a similar code:

```
.\imapsync.exe --host1 imap.gmail.com  --ssl1 --user1 user1@gmail.com --password1  "secretpassword"  ^
               --host2 imap.gmail.com  --ssl2 --user2 user2@yourdomain.com --password2  "secretpassword"  ^
               --maxbytespersecond 10000 --folder "XYZ" --exclude "\[Gmail\]$"

@PAUSE
```

Hope it helps!
Would be good to include it in the classic FAQ.Gmail.txt

However, among the emails in my "XYZ" Label **some messages are also in the default Gmail "Sent" label** (same "from" account address was used). When migrated to G Suite, these messages won´t show up in "Sent" folder, only under the "XYZ" Label.

What parameters should I add to my above code, so that the messages in "XYZ" Label and also in "Send" label, will appear in also in "Send", without duplicating them?

**Comment by gilleslamiral** [comment] 2017-09-05 09:55
Hi Mixali!

A) To sync messages with two labels and sync them with two labels, apply a RAW search command on all folders (so without --folder for simplicity or all folders labeled as wanted):

On Unix:
    imapsync ... --search 'X-GM-RAW "label:XYZ label:ABC"' 

On Windows:

    imapsync.exe ... --search "X-GM-RAW ""label:XYZ label:ABC"""

Gmail won't make duplicates, because Gmail don't make duplicates.

B) The 2-step verification OFF and Access for less secure apps turned ON are already in
https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt

**Comment by mixali0s** [comment] 2017-09-11 11:50
Hi Gilles, Thank you very much for feedback!

I tried your code as suggested: 

```
.\imapsync.exe --host1 imap.gmail.com  --ssl1 --user1 miguel.fvega@gmail.com --password1  "Natalia"  ^
               --host2 imap.gmail.com  --ssl2 --user2 miguel@wega.ws --password2  "polaris12ka.C."  ^
               --maxbytespersecond 10000 --search "X-GM-RAW ""label:XYZ label:Send""" --exclude "\[Gmail\]$" --dry

@PAUSE
```

However, I have the sensation it goes over all default Gmail Labels/Folders... moreover something seems not to work (dry mode, windows), i.e.:

```
Folder    6/10 [[Gmail]/Sent Mail]                 -> [[Gmail]/Sent Mail]                
Host1 folder [[Gmail]/Sent Mail] has 7269 messages in total (mentioned by SELECT)
Host2 folder [[Gmail]/Sent Mail] has 38 messages in total (mentioned by SELECT)
Host1 folder [[Gmail]/Sent Mail] considering 1 messages
Host2 folder [[Gmail]/Sent Mail] considering 1 messages
Use of uninitialized value $h1_msgs[0] in hash slice at script/imapsync line 1771.
Use of uninitialized value $h2_msgs[0] in hash slice at script/imapsync line 1772.
Use of uninitialized value $h1_msgs[0] in hash slice at script/imapsync line 1806.
Use of uninitialized value in split at Mail/IMAPClient/MessageSet.pm line 30.
Host1 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
Use of uninitialized value $h2_msgs[0] in hash slice at script/imapsync line 1860.
Use of uninitialized value in split at Mail/IMAPClient/MessageSet.pm line 30.
Host2 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
msg [Gmail]/Sent Mail/ copying to [Gmail]/Sent Mail 	(not really since --dry mode)
- msg [Gmail]/Sent Mail/ S[0] F[] I[] has RFC822.SIZE null!
- msg [Gmail]/Sent Mail/ skipped.
Folder    7/10 [[Gmail]/Spam]                      -> [[Gmail]/Spam]                     
Host1 folder [[Gmail]/Spam] has 8 messages in total (mentioned by SELECT)
Host2 folder [[Gmail]/Spam] has 2 messages in total (mentioned by SELECT)
Host1 folder [[Gmail]/Spam] considering 1 messages
Host2 folder [[Gmail]/Spam] considering 1 messages
Use of uninitialized value $h1_msgs[0] in hash slice at script/imapsync line 1771.
Use of uninitialized value $h2_msgs[0] in hash slice at script/imapsync line 1772.
Use of uninitialized value $h1_msgs[0] in hash slice at script/imapsync line 1806.
Use of uninitialized value in split at Mail/IMAPClient/MessageSet.pm line 30.
Host1 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
Use of uninitialized value $h2_msgs[0] in hash slice at script/imapsync line 1860.
Use of uninitialized value in split at Mail/IMAPClient/MessageSet.pm line 30.
Host2 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
msg [Gmail]/Spam/ copying to [Gmail]/Spam 	(not really since --dry mode)
- msg [Gmail]/Spam/ S[0] F[] I[] has RFC822.SIZE null!
- msg [Gmail]/Spam/ skipped.
```

AND

```
++++ Statistics
Transfer started on               : Mon Sep 11 11:48:04 2017
Transfer ended on                 : Mon Sep 11 11:51:57 2017
Transfer time                     : 233.6 sec
Folders synced                    : 10/10 synced
Messages transferred              : 0 (could be 0 without dry mode)
Messages skipped                  : 8
Messages found duplicate on host1 : 0
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 0
Messages void (noheader) on host2 : 1
Messages deleted on host1         : 0
Messages deleted on host2         : 0
Total bytes transferred           : 0 (0.000 KiB)
Total bytes duplicate host1       : 0 (0.000 KiB)
Total bytes duplicate host2       : 0 (0.000 KiB)
Total bytes skipped               : 0 (0.000 KiB)
Total bytes error                 : 0 (0.000 KiB)
Message rate                      : 0.0 messages/s
Average bandwidth rate            : 0.0 KiB/s
Memory consumption                : 145.9 MiB
Biggest message                   : 0 bytes (0.000 KiB)
Memory/biggest message ratio      : NA
Start difference host2 - host1    : -2 messages, 0 bytes (0.000 KiB)
Final difference host2 - host1    : -2 messages, 0 bytes (0.000 KiB)
Detected 0 errors
```

Messages skipped according to my test label, should be 16, not 8.

What is wrong?

**Comment by gilleslamiral** [comment] 2017-09-12 20:38
No clue!

**Comment by outoftheboxsol** [comment] 2017-10-07 09:52
I am having the same issue here - everytime I add in a search parameter it fails.

For example:
--search "X-GM-RAW ""to:admin@xxxx.com.au""" 

It always returns zero messages. I also tried just "TO admin@xxxx.com.au" and i get the same thing.

**Comment by gilleslamiral** [comment] 2017-10-07 20:44
Imapsync run on Windows or Unix?

  imapsync.exe ... --search "X-GM-RAW ""to:gilles.lamiral@gmail.com"""

works well for me on Windows.

**Comment by outoftheboxsol** [comment] 2017-10-08 22:57
Im using windows and for me I just get these errors same as above:
Use of uninitialized value in split at Mail/IMAPClient/MessageSet.pm line 30.

**Comment by gilleslamiral** [comment] 2017-10-10 03:34
Confirm that:
  * the command line is inside a .bat or a dos windows
  * the double quotes are all pure ascii double-quotes 
  * try:
    --search "X-GM-RAW ""to:@"""
it should give all messages.

**Comment by outoftheboxsol** [comment] 2017-10-10 03:40
Thanks for your assistance - still not luck.

I'm running it inside the .bat file on windows and have successfully migrated standard accounts that don't require this search feature.

Here is my request:
  .\imapsync.exe --host1 imap.gmail.com --ssl1 --user1 michelle@domain.com.au --password1  "password" --search "X-GM-RAW ""to:@""" ^
 --host2 mail.domain.com.au  --user2 admin@domain.com.au --password2  "password"  ^
--maxbytespersecond 10000 --automap --skipcrossduplicates --dry    

Result I get is this as an example:
ost1 folder    1/16 [ACCOUNTS STUFF]                   Use of uninitialized value $msgs[0] in hash slice at script/imapsync line 5484.
Use of uninitialized value in split at Mail/IMAPClient/MessageSet.pm line 30.
Use of uninitialized value $size in addition (+) at script/imapsync line 5505.

Example stats:
Folders synced                    : 16/16 synced
Messages transferred              : 0 (could be 0 without dry mode)
Messages skipped                  : 7
Messages found duplicate on host1 : 0
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 1
Messages void (noheader) on host2 : 2
Messages deleted on host1         : 0
Messages deleted on host2         : 0

**Comment by gilleslamiral** [comment] 2017-10-11 00:36
Well, no clue for now, can you give a --debugimap1 output?

**Comment by outoftheboxsol** [comment] 2017-10-11 01:03
[transfer_log.zip](https://github.com/imapsync/imapsync/files/1373842/transfer_log.zip)
Here is a dump of the log after adding the debug.

**Comment by gilleslamiral** [comment] 2017-10-11 14:15
Ok, thanks for the log. The first imap SEARCH is enough to understand the problem. We have

`Sending: 29 UID SEARCH X-GM-RAW
Sent 24 bytes
Read: 	29 BAD Could not parse command`
It should have been:
`Sending: 29 UID SEARCH X-GM-RAW "to:@"` or at least
`Sending: 29 UID SEARCH X-GM-RAW to:@` 
There is definitively a quoting issue while passing parameters with double-quotes. Try instead

   imapsync.exe   --search """X-GM-RAW "to:xxx@example.com""""

**Comment by outoftheboxsol** [comment] 2017-10-11 21:24
Worked like a charm! Thanks so much!

Add this to the gmail docs for sure ;)

**Comment by gilleslamiral** [comment] 2018-09-03 02:31
This triple double quotes trick was in fact a bug in  imapsync.exe 1.836
Fixed in new releases and non-regression tests written.

**Closed by gilleslamiral** 2018-09-03 02:31 UTC
Labels: Gmail, Quoting
