### ISSUE TITLE
Ctrl-C not working anymore to abort

### ISSUE THREAD

**Issue by ghost** [imapsync/imapsync#142] opened 2018-06-27 13:27 UTC
I keep getting this

    Got a signal INT (my PID is 2738)
    Hit 2 ctr-c within 2 seconds to exit the program
    Hit only 1 ctr-c to reconnect to both imap servers
    For now only one signal INT within 2 seconds.

**Comment by gilleslamiral** [comment] 2018-06-27 23:53
I've encountered this behavior with some terminals as well. 
An xterm is usually ok but gnome-terminal ignores the double ctrl-c
I don't know why. 
Ctrl-z should work, it doesn't end the process but it gives back the control  
Add kill  <PID> to end the process.

**Comment by gilleslamiral** [comment] 2019-07-23 18:38
Imapsync revision 1.929 added:
Bug fix: When asked to terminate by a signal, kill myself by the signal instead of an exit call. Applied Martin Cracauer's advice on Proper handling of SIGINT/SIGQUIT. I hope it fixes the not always working double-ctrl-c to end the sync.

**Comment by gilleslamiral** [comment] 2019-07-30 09:14
I'm closing this issue. I've seen no recent report about this "double ctr-c not working".

**Comment by 0x3333** [comment] 2019-07-30 17:40
I use not that often imapsync in Docker and I see this issue pretty everytime. Maybe it is related to docker, by I have to kill the process.. it doesn't work.

**Comment by gilleslamiral** [comment] 2019-07-31 12:29
That's interesting, I've just tested this and you're right!

````
docker run gilleslamiral/imapsync imapsync --testslive --simulong 5
...
Are you still here ETA: 16/25 msgs left
Are you still here ETA: 15/25 msgs left
Are you still here ETA: 14/25 msgs left
^C
Got a signal INT (my PID is 1 my PPID is 0)
Hit 2 ctr-c within 2 seconds to exit the program
Hit only 1 ctr-c to reconnect to both imap servers
For now only one signal INT within 2 seconds.
Are you still here ETA: 13/25 msgs left
^CAre you still here ETA: 12/25 msgs left
Got two signals INT within 2 seconds. Exiting...

Got a signal INT (my PID is 1 my PPID is 0). Asked to terminate
Killing myself with signal INT
Are you still here ETA: 11/25 msgs left
Are you still here ETA: 10/25 msgs left
Are you still here ETA: 9/25 msgs left
Are you still here ETA: 8/25 msgs left
...
````

**Comment by gilleslamiral** [comment] 2019-07-31 21:17
The good thing when a developer can reproduce an issue by himself is that soon enough the issue is solved.

I have updated the docker image in order to make ctr-c works well under docker.
https://hub.docker.com/r/gilleslamiral/imapsync

Try it with:
```` 
    docker pull gilleslamiral/imapsync

    docker run gilleslamiral/imapsync imapsync --testslive --simulong 30
    # Hit ctr-c and see!
`````

**Comment by 0x3333** [comment] 2019-08-01 00:31
Wow. That was fast! T
Working great now. Thanks!

**Closed** 2020-02-11 22:53 UTC
Labels: Ctrl-c, Signals
